includes:
  - configs/linear_probing_dinov2_vits14.yaml

model:
  backbone: facebook/dinov2-giant

data:
  train:
    image_processor:
      class_name: transformers.AutoImageProcessor
      pretrained_model_name_or_path: facebook/dinov2-giant
  val:
    image_processor:
      class_name: transformers.AutoImageProcessor
      pretrained_model_name_or_path: facebook/dinov2-giant
