includes:
  - configs/linear_probing_dinov2_vits14.yaml

model:
  backbone: openai/clip-vit-base-patch16

data:
  train:
    image_processor:
      class_name: transformers.CLIPProcessor
      pretrained_model_name_or_path: openai/clip-vit-base-patch16
  val:
    image_processor:
      class_name: transformers.CLIPProcessor
      pretrained_model_name_or_path: openai/clip-vit-base-patch16
