includes:
  - configs/linear_probing_dinov2_vits14.yaml

model:
  backbone: facebook/dino-vitl16

data:
  train:
    image_processor:
      class_name: transformers.ViTImageProcessor
      pretrained_model_name_or_path: facebook/dino-vitl16
  val:
    image_processor:
      class_name: transformers.ViTImageProcessor
      pretrained_model_name_or_path: facebook/dino-vitl16
